In [1]:
import numpy as np

In [2]:
arr = np.array([12,23,45,56,32])

In [3]:
arr

array([12, 23, 45, 56, 32])

In [4]:
print(arr)

[12 23 45 56 32]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.dtype

dtype('int32')

In [7]:
%%timeit
arr = np.array([12,23,34,45,56.88,'Swarali'])

3.77 µs ± 51.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
arr

array([12, 23, 45, 56, 32])

In [9]:
arr.dtype

dtype('int32')

In [10]:
%%timeit
arr=np.array([12,23,34,45,56.88,'Swarali'])

3.76 µs ± 41.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
arr[3]

56

In [12]:
arr.shape

(5,)

In [13]:
arr = np.array([12,23,34,45,56.88])

In [14]:
arr*2

array([ 24.  ,  46.  ,  68.  ,  90.  , 113.76])

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
# 2d

In [21]:
arr1=np.array([[1,2,3],[5,6,7],[9,9,0]])

In [22]:
arr1

array([[1, 2, 3],
       [5, 6, 7],
       [9, 9, 0]])

In [23]:
arr1.shape

(3, 3)

In [24]:
arr1.ndim

2

In [25]:
arr1.flatten()

array([1, 2, 3, 5, 6, 7, 9, 9, 0])

In [29]:
arr1[0:3,0:2]

array([[1, 2],
       [5, 6],
       [9, 9]])

In [30]:
arr

array([12.  , 23.  , 34.  , 45.  , 56.88])

In [31]:
arr.mean()

34.176

In [32]:
arr.min()

12.0

In [33]:
np.unique(arr)

array([12.  , 23.  , 34.  , 45.  , 56.88])